services:
  db:
    image: mysql:latest
    container_name: unified_access_database
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DB_NAME}
    ports:
      - "3360:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./database_user.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - identity_network

volumes:
  db_data:

networks:
  identity_network: 
    driver: bridge